version: '3.8'

services:
  flutter-windows-builder:
    build:
      context: .
      dockerfile: Dockerfile.windows
    container_name: lab-studio-windows-builder
    volumes:
      - ./releases:/output
      - ./.docker-cache:/root/.flutter-cache
    environment:
      - DISPLAY=:99
    working_dir: /app
    command: ["/app/build.sh"]
    
  # 替代方案：使用 GitHub Actions 風格的建置
  flutter-windows-github:
    image: ubuntu:22.04
    container_name: lab-studio-github-builder
    volumes:
      - .:/workspace
      - ./releases:/output
    working_dir: /workspace
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    command: >
      bash -c "
        apt-get update &&
        apt-get install -y curl git &&
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg &&
        echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main' | tee /etc/apt/sources.list.d/github-cli.list &&
        apt-get update &&
        apt-get install -y gh &&
        if [ -n \"$GITHUB_TOKEN\" ]; then
          echo \"$GITHUB_TOKEN\" | gh auth login --with-token &&
          gh workflow run build-windows.yml -f version=\"$(grep 'version:' pubspec.yaml | sed 's/version: //g' | sed 's/+.*//g')\" &&
          echo 'Windows 建置工作流程已觸發！請前往 GitHub Actions 查看進度。'
        else
          echo '請設置 GITHUB_TOKEN 環境變數'
        fi
      "
