name: Build Windows App

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to build (e.g., 1.0.1)'
        required: true
        default: '1.0.1'
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.4'
        channel: 'stable'
    
    - name: Get dependencies
      run: flutter pub get
    
    - name: Build Windows app
      run: flutter build windows --release
    
    - name: Get version from input or tag
      id: get_version
      shell: bash
      run: |
        if [ "${{ github.event.inputs.version }}" != "" ]; then
          echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
        else
          echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        fi
    
    - name: Create Windows release archive
      shell: bash
      run: |
        cd build/windows/x64/runner/Release
        7z a "../../../../../Lab-Studio-v${{ steps.get_version.outputs.VERSION }}-windows.zip" ./*
    
    - name: Upload Windows build artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-app-v${{ steps.get_version.outputs.VERSION }}
        path: Lab-Studio-v${{ steps.get_version.outputs.VERSION }}-windows.zip
    
    - name: Create Release (if tag triggered)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: Lab-Studio-v${{ steps.get_version.outputs.VERSION }}-windows.zip
        draft: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
